# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ["entry.py"],
    pathex=["."],
    binaries=[],
    datas=[],
    hiddenimports=[
        "mnemo",
        "mnemo.cli",
        "mnemo.mcp_server",
        "mnemo.init",
        "mnemo.memory",
        "mnemo.repo_map",
        "mnemo.intelligence",
        "mnemo.knowledge",
        "mnemo.api_discovery",
        "mnemo.code_review",
        "mnemo.errors",
        "mnemo.incidents",
        "mnemo.sprint",
        "mnemo.health",
        "mnemo.team_graph",
        "mnemo.test_intel",
        "mnemo.onboarding",
        "mnemo.dependency_graph",
        "mnemo.workspace",
        "mnemo.analyzers",
        "mnemo.chunking",
        "mnemo.embeddings",
        "mnemo.retrieval",
        "mnemo.vector_index",
        "mnemo.storage",
        "mnemo.clients",
        "mnemo.config",
        "mnemo.doctor",
        "tree_sitter_python",
        "tree_sitter_javascript",
        "tree_sitter_typescript",
        "tree_sitter_go",
        "tree_sitter_c_sharp",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="mnemo",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)
